 "use client";
import {useEffect,useMemo,useState} from "react"; import {Header,Card,Field,fa,num,toast,readJSON} from "@/components/ui";
export default function BudgetItems(){const [items,setItems]=useState<any[]>([]),[f,setF]=useState<any>({code:"",name:"",unit:"",driver:"",logic:"",capacity:"yes",priority:"متوسط"}),[target,setTarget]=useState("90000"),[rate,setRate]=useState("1.05"),[free,setFree]=useState("30000");
useEffect(()=>setItems(readJSON("budgetItems",[])),[]);
const need=num(target)*num(rate),gap=Math.max(need-num(free),0);
const save=()=>{if(!f.name.trim()){toast("نام قلم بودجه الزامی است");return}const a=[...items,{...f,id:Date.now()}];setItems(a);localStorage.setItem("budgetItems",JSON.stringify(a));setF({code:"",name:"",unit:"",driver:"",logic:"",capacity:"yes",priority:"متوسط"});toast("قلم بودجه ذخیره شد")};
return <><Header eyebrow="بودجه‌ریزی / موتور محاسبات" title="تعریف اقلام بودجه و منطق محاسبه نیاز" pill="موتور نیاز"/><section className="hero"><div><small>موتور پایه تحقق‌پذیری بودجه</small><h2>هر قلم بودجه باید منطق محاسبه و نیاز قابل اندازه‌گیری داشته باشد.</h2><p>سیستم از روی هدف، محرک‌ها، ظرفیت عملی و مصرف استاندارد، نیاز و شکاف را استخراج می‌کند.</p></div></section>
<Card><h3>تعریف قلم بودجه</h3><div className="grid"><Field label="کد قلم"><input value={f.code} onChange={e=>setF({...f,code:e.target.value})}/></Field><Field label="نام قلم *"><input value={f.name} onChange={e=>setF({...f,name:e.target.value})}/></Field><Field label="واحد"><input value={f.unit} onChange={e=>setF({...f,unit:e.target.value})}/></Field><Field label="محرک"><input value={f.driver} onChange={e=>setF({...f,driver:e.target.value})}/></Field><Field label="منطق نیاز" full><textarea value={f.logic} onChange={e=>setF({...f,logic:e.target.value})} placeholder="مثلاً هدف تولید × مصرف استاندارد"/></Field><Field label="کنترل ظرفیت"><select value={f.capacity} onChange={e=>setF({...f,capacity:e.target.value})}><option value="yes">دارد</option><option value="no">ندارد</option></select></Field><Field label="اولویت"><select value={f.priority} onChange={e=>setF({...f,priority:e.target.value})}><option>زیاد</option><option>متوسط</option><option>کم</option></select></Field></div><div className="actions"><button className="btn primary" onClick={save}>💾 ذخیره قلم بودجه</button></div></Card>
<Card><h3>اقلام ثبت‌شده</h3><div className="table-wrap"><table className="table"><thead><tr><th>کد</th><th>نام</th><th>محرک</th><th>منطق نیاز</th><th>کنترل ظرفیت</th><th>اولویت</th></tr></thead><tbody>{items.map(x=><tr key={x.id}><td>{x.code||"—"}</td><td>{x.name}</td><td>{x.driver||"—"}</td><td>{x.logic||"—"}</td><td>{x.capacity==="yes"?"دارد":"ندارد"}</td><td>{x.priority}</td></tr>)}</tbody></table></div></Card>
<Card><h3>پیش‌نمایش موتور نیازسنجی</h3><p className="hint">نمونه: هدف × مصرف استاندارد = نیاز؛ سپس نیاز با ظرفیت آزاد مقایسه می‌شود.</p><div className="simulation"><div className="sim"><small>هدف تولید</small><b>{fa(num(target))}</b><span>تن</span></div><div className="sim-arrow">×</div><div className="sim"><small>مصرف استاندارد</small><b>{fa(num(rate))}</b><span>واحد / تن</span></div><div className="sim-arrow">=</div><div className="sim accent"><small>نیاز محاسبه‌شده</small><b>{fa(need)}</b><span>واحد</span></div><div className="sim"><small>ظرفیت آزاد</small><b>{fa(num(free))}</b><span>واحد ظرفیت</span></div><div className="sim warn"><small>شکاف</small><b>{fa(gap)}</b><span>واحد</span></div></div></Card></> }