 "use client";
import {useEffect,useState} from "react"; import {Header,Card,Field,toast} from "@/components/ui";
export default function Company(){const [type,setType]=useState("company");const [f,setF]=useState<any>({name:"",trade:"",nid:"",reg:"",date:"",eco:"",ceo:"",phone:"",mobile:"",email:"",web:"",postal:"",address:"",province:"انتخاب استان",city:"",holdingName:"",holdingNid:""});
useEffect(()=>{try{const x=JSON.parse(localStorage.getItem("budgetOrg")||"null");if(x){setF(x);setType(x.type||"company")}}catch{}},[]);
const set=(k:string,v:string)=>setF((x:any)=>({...x,[k]:v}));
const save=()=>{if(!f.name.trim()){toast("نام شرکت الزامی است");return}if(type==="holding"&&!f.holdingName.trim()){toast("نام هلدینگ الزامی است");return}localStorage.setItem("budgetOrg",JSON.stringify({...f,type}));toast("اطلاعات سازمان ذخیره شد")};
return <><Header eyebrow="اطلاعات پایه / معرفی شرکت" title="معرفی شرکت"/><Card><h3>نوع سازمان</h3><div className="types">{[["company","🏢","شرکت مستقل","سازمان دارای شخصیت حقوقی مستقل"],["holding","🏛️","هلدینگ","شرکت مادر دارای شرکت‌های زیرمجموعه"]].map(([v,ic,t,d])=><label key={v} className={"type "+(type===v?"selected":"")}><input type="radio" checked={type===v} onChange={()=>setType(v)} />{ic} <b>{t}</b><small>{d}</small></label>)}</div></Card>
<Card><h3>اطلاعات ثبتی</h3><div className="grid">{[["name","نام شرکت *"],["trade","نام تجاری"],["nid","شناسه ملی"],["reg","شماره ثبت"],["date","تاریخ ثبت"],["eco","کد اقتصادی"],["ceo","مدیرعامل"]].map(([k,l])=><Field key={k} label={l}><input value={f[k]||""} onChange={e=>set(k,e.target.value)}/></Field>)}</div></Card>
<Card><h3>اطلاعات تماس و نشانی</h3><div className="grid"><Field label="استان"><select value={f.province} onChange={e=>set("province",e.target.value)}><option>انتخاب استان</option><option>تهران</option><option>مازندران</option><option>اصفهان</option><option>خراسان رضوی</option></select></Field>{[["city","شهر"],["phone","تلفن"],["mobile","موبایل"],["email","ایمیل"],["web","وب‌سایت"],["postal","کد پستی"]].map(([k,l])=><Field key={k} label={l}><input value={f[k]||""} onChange={e=>set(k,e.target.value)}/></Field>)}<Field label="آدرس" full><textarea value={f.address||""} onChange={e=>set("address",e.target.value)}/></Field></div></Card>
{type==="holding"&&<Card><h3>اطلاعات هلدینگ</h3><div className="grid"><Field label="نام هلدینگ *"><input value={f.holdingName||""} onChange={e=>set("holdingName",e.target.value)}/></Field><Field label="شناسه ملی هلدینگ"><input value={f.holdingNid||""} onChange={e=>set("holdingNid",e.target.value)}/></Field></div><p className="hint">پس از ذخیره، صفحه تعریف شرکت‌های زیرمجموعه فعال می‌شود.</p></Card>}
<div className="actions"><button className="btn primary" onClick={save}>💾 ذخیره اطلاعات</button></div></> }