 "use client";
import {useEffect,useState} from "react"; import {Header,Card,Field,fa,num,toast,readJSON} from "@/components/ui";
export default function Goals(){const [goals,setGoals]=useState<any[]>([]),[f,setF]=useState<any>({year:"۱۴۰۵",level:"شرکت",title:"",target:"",practical:"",occupied:"",driver:"محرک هدف"});
useEffect(()=>setGoals(readJSON("budget_goals_v1",[])),[]);
const free=Math.max(num(f.practical)-num(f.occupied),0),gap=Math.max(num(f.target)-free,0);
const status=num(f.target)<=free?"قابل تحقق با ظرفیت آزاد":"نیازمند ظرفیت/منبع جبرانی";
const save=()=>{if(!f.title.trim()||!f.target){toast("عنوان و مقدار هدف الزامی است");return}const x={...f,id:Date.now(),free,gap,status};const a=[...goals,x];setGoals(a);localStorage.setItem("budget_goals_v1",JSON.stringify(a));toast("هدف ذخیره شد")};
return <><Header eyebrow="بودجه‌ریزی / اهداف" title="اهداف و چارچوب اولیه بودجه" pill="ورودی موتور بودجه"/><Card><h2>تعریف هدف</h2><p className="hint">هدف، ظرفیت عملی و ظرفیت مشغول ورودی مستقیم موتور تحقق‌پذیری هستند.</p><div className="grid"><Field label="سال"><input value={f.year} onChange={e=>setF({...f,year:e.target.value})}/></Field><Field label="سطح"><select value={f.level} onChange={e=>setF({...f,level:e.target.value})}><option>هلدینگ</option><option>شرکت</option><option>پروژه</option></select></Field><Field label="عنوان هدف *"><input value={f.title} onChange={e=>setF({...f,title:e.target.value})}/></Field><Field label="مقدار هدف *"><input value={f.target} onChange={e=>setF({...f,target:e.target.value})}/></Field><Field label="ظرفیت عملی"><input value={f.practical} onChange={e=>setF({...f,practical:e.target.value})}/></Field><Field label="ظرفیت مشغول"><input value={f.occupied} onChange={e=>setF({...f,occupied:e.target.value})}/></Field><Field label="محرک هدف"><select value={f.driver} onChange={e=>setF({...f,driver:e.target.value})}><option>محرک هدف</option><option>ترکیبی</option></select></Field></div></Card>
<Card><h2>خلاصه ورودی موتور بودجه</h2><div className="calc"><div className="metric"><span>هدف</span><strong>{fa(num(f.target))}</strong></div><div className="metric"><span>ظرفیت آزاد</span><strong>{fa(free)}</strong></div><div className="metric"><span>شکاف</span><strong>{fa(gap)}</strong></div></div><p className="hint">وضعیت: <b>{status}</b></p><div className="actions"><button className="btn primary" onClick={save}>ذخیره هدف</button></div></Card>
<Card><h2>اهداف ثبت‌شده</h2><div className="table-wrap"><table className="table"><thead><tr><th>سال</th><th>سطح</th><th>هدف</th><th>مقدار</th><th>ظرفیت آزاد</th><th>شکاف</th><th>وضعیت</th></tr></thead><tbody>{goals.map(x=><tr key={x.id}><td>{x.year}</td><td>{x.level}</td><td>{x.title}</td><td>{fa(num(x.target))}</td><td>{fa(x.free)}</td><td>{fa(x.gap)}</td><td><span className={"badge "+(x.gap?"warn":"")}>{x.status}</span></td></tr>)}</tbody></table></div></Card></> }